name: Deploy to ECR

on:
  push:
    tags:
      - 'ecr-v*'

jobs:
  Release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    # Getting tag name for docker image and full tag name.
    - name: Get tag version
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_TAG_DOCKER_IMAGE::${GITHUB_REF#refs/tags/ecr-v}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    # Deploying image to Elastic Container Registry
    - run: docker build . --tag yii-app:${{ steps.branch_name.outputs.SOURCE_TAG_DOCKER_IMAGE }}
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ap-southeast-1
        image: yii-app:${{ steps.branch_name.outputs.SOURCE_TAG_DOCKER_IMAGE }}

    # Notify engineers via slack
    - name: Notify slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_OPEN_SOURCE }}
        SLACK_USERNAME: "Open Source Activities"
        SLACK_TITLE: "New Version Release!"
        SLACK_MESSAGE: "\n\n === ${{ github.repository }} (${{ steps.branch_name.outputs.SOURCE_TAG }}) ==="
        SLACK_FOOTER: "Powered by Element Creative Studio"
        SLACK_ICON: "https://cdn.elementcreativestudio.com/github.png"